---
title: "FinalProject"
output: html_document
---

# Set-up
```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("limma")
BiocManager::install("Glimma")
BiocManager::install("edgeR")
BiocManager::install("Homo.sapiens")
library(limma)
library(Glimma)
library(edgeR)
library(Homo.sapiens)
```

#Data pre-processing

## Reading in count-data
```{r}
setwd ('~/Desktop/TRGN510/trgn510_fall20/')
files <- c("7d9b1591-42eb-4d02-978e-0a194d498d6c.htseq.counts","8a705b7c-4607-4ede-9486-cbeb1191004e.htseq.counts","7922baf0-3d03-4b00-afa4-96c272583861.htseq.counts","77213cf0-8029-4470-af4e-a25fce4d4681.htseq.counts","39423508-c376-4582-80c0-ddcf81167d74.htseq.counts","b918773c-1920-42aa-8493-22344ea5ac49.htseq.counts","bcd07e88-975d-4f4b-9b2e-33ad0f2211f3.htseq.counts","dab350c1-f3b4-488b-8c48-7f8339e4a554.htseq.counts","e3bee637-c8c3-4953-842c-11b16ea1bf73.htseq.counts","e15d3de5-f141-487f-8262-8b0d20563c76.htseq.counts",
           "0b4a2460-8f70-4f60-85b3-95d0012d38c8.htseq.counts","6f8c77f2-67de-411d-a03d-5fef3216b71b.htseq.counts","7d6848a5-7dfc-4494-9095-4e89fea1aee5.htseq.counts","9ef0c6dd-6e38-41fd-aff6-ae0800c7755d.htseq.counts","46f8e9d8-032c-471e-876c-1af0ac3b1cee.htseq.counts","a0cb35f5-0d64-4fb9-9747-acf4cfc88012.htseq.counts","aeb170cb-b227-4033-9e15-3d6d6102d856.htseq.counts","cd068064-b4cc-4a34-94be-ce95e3342c6d.htseq.counts","d076a8ce-ccc9-4b1d-9486-ad4e63b6f603.htseq.counts","dd752d51-02c4-4850-a355-18770d9be482.htseq.counts")
read.delim(files[1],nrow=5,header=FALSE)
getwd()
```

```{r}
x <- readDGE(files, columns=c(1,2))
class(x)
```

```{r}
dim(x)
```

## Organising sample information
```{r}
samplenames <- substring(colnames(x), 12, nchar(colnames(x)))
samplenames
```

```{r}
colnames(x) <- samplenames
group <- c(rep("Age 10-50",10),rep("Age 51-100",10))
x$samples$group <- group
x$samples
```

## Organising gene annotations
```{r}
install.packages("gsubfn")
library(gsubfn)
geneid <- rownames(x)
geneid <- gsub("\\.[0-9]*$","",geneid)
head(geneid)
```

```{r}
genes <- select(Homo.sapiens, 
                keys=geneid,
                columns=c("GENEID","GENENAME"),
                keytype="ENSEMBL")
genes <- select(Homo.sapiens, keys=geneid, columns=c("SYMBOL", "TXCHROM"), 
                keytype="ENSEMBL")
head(genes)
```

```{r}
genes <- genes[!duplicated(genes$ENSEMBL),]
```

```{r}
x$genes <- genes
x
```

# Data pre-processing

## Transformations from the raw-scale
```{r}
cpm <- cpm(x)
lcpm <- cpm(x, log=TRUE)

L <- mean(x$samples$lib.size) * 1e-6
M <- median(x$samples$lib.size) * 1e-6
c(L, M)
```

```{r}
summary(lcpm)
```

## Removing genes that are lowly expressed
```{r}
table(rowSums(x$counts==0)==9)
```

```{r}
keep.exprs <- filterByExpr(x, group=group)
x <- x[keep.exprs,, keep.lib.sizes=FALSE]
dim(x)
```

```{r}
lcpm.cutoff <- log2(10/M + 2/L)
library(RColorBrewer)
nsamples <- ncol(x)
col <- brewer.pal(nsamples, "Paired")
par(mfrow=c(1,2))
plot(density(lcpm[,1]), col=col[1], lwd=2, ylim=c(0,0.26), las=2, main="", xlab="")
title(main="A. Raw data", xlab="Log-cpm")
abline(v=lcpm.cutoff, lty=3)
for (i in 2:nsamples){
den <- density(lcpm[,i])
lines(den$x, den$y, col=col[i], lwd=2)
}
legend("topright", samplenames, text.col=col, bty="n")
lcpm <- cpm(x, log=TRUE)
plot(density(lcpm[,1]), col=col[1], lwd=2, ylim=c(0,0.26), las=2, main="", xlab="")
title(main="B. Filtered data", xlab="Log-cpm")
abline(v=lcpm.cutoff, lty=3)
for (i in 2:nsamples){
den <- density(lcpm[,i])
lines(den$x, den$y, col=col[i], lwd=2)
}
legend("topright", samplenames, text.col=col, bty="n")
```

## Normalising gene expression distributions
```{r}
x <- calcNormFactors(x, method = "TMM")
x$samples$norm.factors
```

```{r}
x2 <- x
x2$samples$norm.factors <- 1
x2$counts[,1] <- ceiling(x2$counts[,1]*0.05)
x2$counts[,2] <- x2$counts[,2]*5
```

```{r}
par(mfrow=c(1,2))
lcpm <- cpm(x2, log=TRUE)
boxplot(lcpm, las=2, col=col, main="")
title(main="A. Example: Unnormalised data",ylab="Log-cpm")
x2 <- calcNormFactors(x2)  
x2$samples$norm.factors
```

```{r}
lcpm <- cpm(x2, log=TRUE)
boxplot(lcpm, las=2, col=col, main="")
title(main="B. Example: Normalised data",ylab="Log-cpm")
```

## Unsupervised clustering of samples
```{r}
lcpm <- cpm(x, log=TRUE)
par(mfrow=c(1,2))
group
levels(group) <-  brewer.pal(nlevels(group), "Set1")
col.group <- as.character(group)
col.group <- c("purple","orange")[group]
plotMDS(lcpm, labels=group, col=col.group)
title(main="A. Sample groups")
```

```{r}
glMDSPlot(lcpm, groups=group)
```

